import {
  FaFacebook,
  FaInstagram,
  FaLinkedin,
  FaGithub,
  FaSnapchat,
  FaPinterest,
  FaTumblr,
  FaReddit,
  FaYoutube,
  FaGooglePlus,
  FaWhatsapp,
  FaSkype,
  FaVimeo,
  FaSoundcloud,
  FaSpotify,
  FaStackOverflow,
  FaGitlab,
  FaBitbucket,
  FaJira,
  FaDocker,
  FaNpm,
  FaDev,
  FaMedium,
  FaFreeCodeCamp,
  FaCodepen,
  FaHackerrank,
  FaDribbble,
  FaBehance,
} from "react-icons/fa";
import { BsTwitterX } from "react-icons/bs";

export const socialMediaIcons: Record<string, JSX.Element> = {
  facebook: <FaFacebook />,
  twitter: <BsTwitterX />,
  instagram: <FaInstagram />,
  linkedin: <FaLinkedin />,
  github: <FaGithub />,
  snapchat: <FaSnapchat />,
  pinterest: <FaPinterest />,
  tumblr: <FaTumblr />,
  reddit: <FaReddit />,
  youtube: <FaYoutube />,
  googleplus: <FaGooglePlus />,
  whatsapp: <FaWhatsapp />,
  skype: <FaSkype />,
  vimeo: <FaVimeo />,
  soundcloud: <FaSoundcloud />,
  spotify: <FaSpotify />,
  stackoverflow: <FaStackOverflow />,
  gitlab: <FaGitlab />,
  bitbucket: <FaBitbucket />,
  jira: <FaJira />,
  docker: <FaDocker />,
  npm: <FaNpm />,
  dev: <FaDev />,
  medium: <FaMedium />,
  freecodecamp: <FaFreeCodeCamp />,
  codepen: <FaCodepen />,
  hackerrank: <FaHackerrank />,
  dribbble: <FaDribbble />,
  behance: <FaBehance />,
};
