import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React from "react";
import Navbar from "@/components/Navbar";
import { Analytics } from "@vercel/analytics/react";
import Link from "next/link";
import "@radix-ui/themes/styles.css";
const inter = Inter({ subsets: ["latin"] });
import { Theme, ThemePanel } from "@radix-ui/themes";

export const metadata: Metadata = {
  title: {
    template: "%s | GPV",
    default: "Github Profile Viewer",
  },
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
    shortcut: "/favicon.png",
    apple: "/favicon.png",
  },
};

export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "white" },
    { media: "(prefers-color-scheme: dark)", color: "black" },
  ],
  width: "device-width",
  initialScale: 1,
  userScalable: true,
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head></head>
      <body
        className={`${inter.className} flex min-h-screen w-full justify-center px-1 md:px-4 transition-all duration-1000`}
      >
        <Theme
          appearance="dark"
          accentColor="gray"
          grayColor="slate"
          radius="large"
          scaling="110%"
        >
          <main className=" flex 2xl:w-[70rem] lg:w-[60rem] md:w-[40rem] sm:w-[30rem] flex-col gap-4 p-2 pt-4 transition-all duration-1000">
            <Navbar />
            {children}
          </main>
          {/* <ThemePanel /> */}
        </Theme>
        <Analytics />
      </body>
    </html>
  );
}
