import {
  FaJs,
  FaPython,
  FaJava,
  FaReact,
  FaNode,
  FaHtml5,
  FaCss3,
} from "react-icons/fa";
import {
  SiCplusplus,
  SiRuby,
  SiGo,
  SiCsharp,
  SiPhp,
  SiSwift,
  SiTypescript,
  SiScala,
  SiKotlin,
  SiPerl,
  SiRust,
  SiHaskell,
  SiLua,
  SiDart,
  SiR,
  SiShell,
} from "react-icons/si";

export const languageIcons: Record<string, JSX.Element> = {
  JavaScript: <FaJs />,
  Python: <FaPython />,
  Java: <FaJava />,
  React: <FaReact />,
  NodeJS: <FaNode />,
  HTML: <FaHtml5 />,
  CSS: <FaCss3 />,
  "C++": <SiCplusplus />,
  Ruby: <SiRuby />,
  Go: <SiGo />,
  CSharp: <SiCsharp />,
  PHP: <SiPhp />,
  Swift: <SiSwift />,
  TypeScript: <SiTypescript />,
  Scala: <SiScala />,
  Kotlin: <SiKotlin />,
  Perl: <SiPerl />,
  Rust: <SiRust />,
  Haskell: <SiHaskell />,
  Lua: <SiLua />,
  Dart: <SiDart />,
  R: <SiR />,
  Shell: <SiShell />,
};
